PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX spo: <https://w3id.org/steel/ProcessOntology/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

DELETE {
  ?unit a qudt:Unit . 
  ?unit spo:hasUnitLabel ?label .
  ?unit spo:hasShortId ?shortId .
} WHERE {
  ?unit a qudt:Unit .  
  OPTIONAL { ?unit spo:hasUnitLabel ?label } .
  OPTIONAL { ?unit spo:hasShortId ?shortId } .
  FILTER ( ! STRSTARTS( STR(?unit), "https://w3id.org/steel/ProcessOntology/" ) ).
}